import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, FileText, Download, Shield, Printer, CheckCircle } from 'lucide-react';
import { DUMMY_INCIDENTS, INFRA_LABELS, STATUS_COLORS } from '@/lib/dummyData';
import jsPDF from 'jspdf';

const AUTHORITY_OPTIONS = [
  { id: 'saps', label: 'SAPS Case Docket', icon: '🚔', color: '#1A6B3C' },
  { id: 'eskom', label: 'Eskom Fault Report', icon: '⚡', color: '#C9A84C' },
  { id: 'municipality', label: 'Municipality Report', icon: '🏛️', color: '#4A90D9' },
  { id: 'gpg', label: 'GPG Infrastructure Report', icon: '🛡️', color: '#8B6914' },
];

function formatDate(iso) {
  return new Date(iso).toLocaleString('en-ZA', {
    day: '2-digit', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

export default function OfficialReportModal({ onClose }) {
  const [selectedAuthority, setSelectedAuthority] = useState('saps');
  const [selectedIncidents, setSelectedIncidents] = useState(
    DUMMY_INCIDENTS.filter(i => i.status === 'active').map(i => i.id)
  );
  const [generated, setGenerated] = useState(false);
  const [generating, setGenerating] = useState(false);

  const toggleIncident = (id) => {
    setSelectedIncidents(prev =>
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
    );
  };

  const authority = AUTHORITY_OPTIONS.find(a => a.id === selectedAuthority);
  const incidents = DUMMY_INCIDENTS.filter(i => selectedIncidents.includes(i.id));

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => {
      generatePDF();
      setGenerating(false);
      setGenerated(true);
    }, 1200);
  };

  const generatePDF = () => {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageW = 210;
    const margin = 18;
    let y = 20;

    // Header
    doc.setFillColor(10, 10, 15);
    doc.rect(0, 0, pageW, 40, 'F');
    doc.setTextColor(201, 168, 76);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('CableWatch', margin, 16);
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text('Gauteng Provincial Government — Infrastructure Threat Intelligence', margin, 23);
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text(`${authority.label.toUpperCase()}`, margin, 33);
    y = 50;

    // Report meta
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated: ${formatDate(new Date().toISOString())}`, margin, y);
    doc.text(`Reference: CW-RPT-${Date.now().toString().slice(-8)}`, pageW - margin - 50, y);
    y += 6;
    doc.text(`Total incidents included: ${incidents.length}`, margin, y);
    y += 10;

    // Divider
    doc.setDrawColor(201, 168, 76);
    doc.setLineWidth(0.5);
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    // Summary
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text('INCIDENT SUMMARY', margin, y);
    y += 7;

    incidents.forEach((inc, idx) => {
      if (y > 260) { doc.addPage(); y = 20; }

      doc.setFillColor(245, 245, 248);
      doc.roundedRect(margin, y, pageW - margin * 2, 38, 2, 2, 'F');

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(20, 20, 20);
      doc.text(`${idx + 1}. ${inc.title}`, margin + 3, y + 7);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(80, 80, 80);
      doc.text(`Ref: ${inc.case_reference}  |  Status: ${STATUS_COLORS[inc.status]?.label || inc.status}  |  Severity: ${inc.severity_score}/10`, margin + 3, y + 13);
      doc.text(`Location: ${inc.address}, ${inc.area_name} — Ward ${inc.ward_number}, ${inc.municipality}`, margin + 3, y + 19);
      doc.text(`Type: ${INFRA_LABELS[inc.infrastructure_type] || inc.infrastructure_type}  |  Reported: ${formatDate(inc.reported_at)}`, margin + 3, y + 25);

      const descLines = doc.splitTextToSize(inc.description, pageW - margin * 2 - 6);
      const shortDesc = descLines.slice(0, 1).join('');
      doc.text(shortDesc.length > 90 ? shortDesc.slice(0, 90) + '...' : shortDesc, margin + 3, y + 31);

      y += 43;
    });

    // Footer
    if (y > 260) { doc.addPage(); y = 20; }
    y += 5;
    doc.setDrawColor(201, 168, 76);
    doc.line(margin, y, pageW - margin, y);
    y += 6;
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text('This report was auto-generated by CableWatch — Gauteng Community Intelligence Platform.', margin, y);
    doc.text('For emergencies: SAPS 10111 | Eskom Fault Line 08600 37566 | Emergency 112', margin, y + 5);

    doc.save(`CableWatch_${selectedAuthority.toUpperCase()}_Report_${Date.now()}.pdf`);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[900] flex items-end sm:items-center justify-center">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
          className="absolute inset-0 bg-black/70 backdrop-blur-sm"
          onClick={onClose}
        />

        {/* Panel */}
        <motion.div
          initial={{ opacity: 0, y: 60 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 60 }}
          transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          className="relative w-full max-w-lg max-h-[90vh] overflow-y-auto glass-panel rounded-t-2xl sm:rounded-2xl"
        >
          {/* Header */}
          <div className="sticky top-0 glass-panel border-b border-gold/10 px-5 py-4 flex items-center justify-between z-10">
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl bg-gold/10 flex items-center justify-center">
                <FileText className="w-5 h-5 text-gold" />
              </div>
              <div>
                <h3 className="font-heading font-bold text-white text-sm">Official Report Generator</h3>
                <p className="text-[11px] text-muted-foreground">Export for SAPS, Eskom or Municipality</p>
              </div>
            </div>
            <button onClick={onClose} className="w-8 h-8 rounded-lg hover:bg-gold/10 flex items-center justify-center transition-colors">
              <X className="w-4 h-4 text-muted-foreground" />
            </button>
          </div>

          <div className="px-5 py-4 space-y-5">
            {/* Authority selection */}
            <div>
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">Report Type</p>
              <div className="grid grid-cols-2 gap-2">
                {AUTHORITY_OPTIONS.map(opt => (
                  <button
                    key={opt.id}
                    onClick={() => setSelectedAuthority(opt.id)}
                    className={`flex items-center gap-2.5 px-3 py-3 rounded-xl border text-left transition-all ${
                      selectedAuthority === opt.id
                        ? 'border-gold/40 bg-gold/10'
                        : 'border-gold/5 bg-surface-dark hover:border-gold/15'
                    }`}
                  >
                    <span className="text-lg">{opt.icon}</span>
                    <span className={`text-xs font-semibold ${selectedAuthority === opt.id ? 'text-gold' : 'text-white'}`}>
                      {opt.label}
                    </span>
                  </button>
                ))}
              </div>
            </div>

            {/* Incident selection */}
            <div>
              <div className="flex items-center justify-between mb-3">
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Include Incidents</p>
                <span className="text-xs text-gold mono-num">{selectedIncidents.length} selected</span>
              </div>
              <div className="space-y-2 max-h-52 overflow-y-auto pr-1">
                {DUMMY_INCIDENTS.map(inc => {
                  const statusStyle = STATUS_COLORS[inc.status];
                  const isSelected = selectedIncidents.includes(inc.id);
                  return (
                    <button
                      key={inc.id}
                      onClick={() => toggleIncident(inc.id)}
                      className={`w-full flex items-start gap-3 px-3 py-2.5 rounded-xl border text-left transition-all ${
                        isSelected
                          ? 'border-gold/20 bg-gold/5'
                          : 'border-transparent bg-surface-dark hover:border-gold/10'
                      }`}
                    >
                      <div className={`w-4 h-4 mt-0.5 rounded flex-shrink-0 flex items-center justify-center border transition-all ${
                        isSelected ? 'bg-gold border-gold' : 'border-gold/20'
                      }`}>
                        {isSelected && <CheckCircle className="w-3 h-3 text-surface-black" />}
                      </div>
                      <div className="min-w-0 flex-1">
                        <p className="text-xs font-semibold text-white truncate">{inc.title}</p>
                        <div className="flex items-center gap-2 mt-0.5">
                          <span className="text-[10px] text-muted-foreground">{inc.area_name}</span>
                          <span className={`text-[10px] font-semibold ${statusStyle?.textClass || 'text-gold'}`}>
                            {statusStyle?.label}
                          </span>
                        </div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Generate button */}
            {!generated ? (
              <button
                onClick={handleGenerate}
                disabled={selectedIncidents.length === 0 || generating}
                className={`w-full py-3.5 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${
                  selectedIncidents.length > 0 && !generating
                    ? 'btn-gold'
                    : 'bg-surface-mid text-muted-foreground cursor-not-allowed'
                }`}
              >
                {generating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-surface-black/30 border-t-surface-black rounded-full animate-spin" />
                    Generating PDF…
                  </>
                ) : (
                  <>
                    <Download className="w-4 h-4" />
                    Generate {authority?.label}
                  </>
                )}
              </button>
            ) : (
              <div className="space-y-2">
                <div className="w-full py-3 rounded-xl bg-gpg-green/10 border border-gpg-green/20 flex items-center justify-center gap-2 text-sm font-semibold" style={{ color: '#1A6B3C' }}>
                  <CheckCircle className="w-4 h-4" />
                  PDF Downloaded Successfully
                </div>
                <button
                  onClick={() => setGenerated(false)}
                  className="w-full py-2.5 rounded-xl border border-gold/15 text-gold text-sm font-semibold hover:bg-gold/5 transition-colors"
                >
                  Generate Another Report
                </button>
              </div>
            )}

            {/* Emergency contacts */}
            <div className="rounded-xl bg-surface-dark border border-gold/8 px-4 py-3">
              <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-2">Emergency Contacts</p>
              <div className="space-y-1">
                {[
                  ['SAPS Emergency', '10111'],
                  ['Eskom Fault Line', '0860 037 566'],
                  ['City Power', '011 490 7484'],
                  ['Emergency Services', '112'],
                ].map(([label, num]) => (
                  <div key={label} className="flex justify-between items-center">
                    <span className="text-xs text-muted-foreground">{label}</span>
                    <a href={`tel:${num.replace(/\s/g, '')}`} className="mono-num text-xs font-bold text-gold hover:text-gold-light transition-colors">
                      {num}
                    </a>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
